import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {HelloWorld} from "dsl/src";
import Button, {ButtonType} from "dsl/src/Button/Button";
import {css} from "dsl/helpers/css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <HelloWorld/>
                <div className={css("mb-4")}>
                    <Button>Hello there!</Button>
                </div>
                <Button type={ButtonType.White}>Secondary Button</Button>
            </main>
        </div>
    )
}

export default Home
