import { PivotControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { css } from "dsl/helpers/css";
import Head from "next/head";
import { Suspense, useEffect, useState } from "react";
import { BufferGeometry } from "three";
import { STLLoader } from "three/examples/jsm/loaders/STLLoader";

export default function Home() {
  const [geometry, setGeometry] = useState<BufferGeometry>();
  useEffect(() => {
    const stlLoader = new STLLoader();
  }, []);
  return (
    <>
      <Head>
        <title>Much Wow Film</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css("bg-pixels-yellow-100", "grow")}>
        <Canvas camera={{ position: [0, 0, 4.5] }}>
          <Suspense fallback={null}>
            <PivotControls visible={false} lineWidth={1} depthTest={false}>
              {/* <Model
                rotationSpeed={rotationSpeed}
                url={model.url}
                scale={model.scale}
                position={model.position}
              /> */}
            </PivotControls>
            {/* {isDev() && (
                    <GizmoHelper alignment="bottom-right" margin={[80, 80]}>
                      <GizmoViewport
                        axisColors={["red", "green", "blue"]}
                        labelColor="black"
                      />
                    </GizmoHelper>
                  )} */}
            <ambientLight intensity={0.5} />
          </Suspense>
        </Canvas>
      </main>
    </>
  );
}
