import {
  GizmoHelper,
  GizmoViewport,
  PivotControls,
  useGLTF,
  useVideoTexture,
} from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { css } from "dsl/helpers/css";
import Head from "next/head";
import { Suspense } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Much Wow Film</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={css(
          "bg-pixels-yellow-100",
          "grow",
          "flex",
          "flex-col",
          "items-center",
          "justify-center"
        )}
      >
        <div
          className={css(
            "relative",
            "max-w-xl",
            "w-full",
            "shrink-0",
            "border-[1px]",
            "border-solid",
            "border-black",
            "h-[500px]"
          )}
        >
          <Canvas camera={{ position: [0, 0, 20] }} className={css("grow")}>
            <Suspense fallback={null}>
              <PivotControls visible={false} lineWidth={1} depthTest={false}>
                <Model />
              </PivotControls>
              <GizmoHelper alignment="bottom-right" margin={[80, 80]}>
                <GizmoViewport
                  axisColors={["red", "green", "blue"]}
                  labelColor="black"
                />
              </GizmoHelper>
              <ambientLight intensity={0.5} />
            </Suspense>
          </Canvas>
        </div>
      </main>
    </>
  );
}

const Model = () => {
  const { nodes, materials, scene } = useGLTF("./models/doge.glb");
  const texture = useVideoTexture("./videos/wow.mp4", { autoplay: true });
  return (
    <mesh position={[0, 0, 18.5]}>
      {/* <primitive object={scene} /> */}
      <planeGeometry args={[1.777777778, 1]} />
      <meshBasicMaterial map={texture} toneMapped={false} />
    </mesh>
  );
};
